spring.application.name=demo
spring.datasource.url=jdbc:postgresql://ep-divine-feather-aoctfjsi.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_iDJuW68AwcRx

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update